version: '3'
services:
  app:
    build:
      context: ./docker/app
    volumes:
      - ./html:/var/www/html
    environment:
      TZ: Asia/Tokyo
      VIRTUAL_HOST: phpjs1.yuzunoha.net
      LETSENCRYPT_HOST: phpjs1.yuzunoha.net
      LETSENCRYPT_EMAIL: studysteadystandby@gmail.com
  db:
    build:
      context: ./docker/db
    volumes:
      - ./docker/db/var_lib_mysql:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bbs
      - TZ=Asia/Tokyo
networks:
  default:
    external:
      name: nginx-proxy
